CREATE TABLE IF NOT EXISTS SalesOrder
(
    SalesOrderID           INT                 NOT NULL COMMENT 'Primary key.',
    SalesOrderDetailID     INT                 NOT NULL COMMENT 'Primary key. One incremental unique number per product sold.',
    RevisionNumber         TINYINT             NOT NULL COMMENT 'Incremental number to track changes to the sales order over time.',
    OrderDate              DATETIME            NOT NULL COMMENT 'Dates the sales order was created.',
    DueDate                DATETIME            NOT NULL COMMENT 'Date the order is due to the customer.',
    ShipDate               DATETIME COMMENT 'Date the order was shipped to the customer.',
    Status                 TINYINT             NOT NULL COMMENT 'Order current status. 1 = In process; 2 = Approved; 3 = Backordered; 4 = Rejected; 5 = Shipped; 6 = Cancelled',
    OnlineOrderFlag        BIT                 NOT NULL COMMENT '0 = Order placed by sales person. 1 = Order placed online by customer.',
    SalesOrderNumber       NVARCHAR(30)        NOT NULL COMMENT 'Unique sales order identification number.',
    PurchaseOrderNumber    NVARCHAR(25) COMMENT 'Customer purchase order number reference. ',
    AccountNumber          NVARCHAR(15) COMMENT 'Financial accounting number reference.',
    CustomerID             INT                 NOT NULL COMMENT 'Customer identification number. Foreign key to Customer.CustomerID.',
    ShipToAddressID        INT COMMENT 'The ID of the location to send goods.  Foreign key to the Address table.',
    BillToAddressID        INT COMMENT 'The ID of the location to send invoices.  Foreign key to the Address table.',
    ShipMethod             NVARCHAR(50)        NOT NULL COMMENT 'Shipping method. Foreign key to ShipMethod.ShipMethodID.',
    CreditCardApprovalCode VARCHAR(15) COMMENT 'Approval code provided by the credit card company.',
    SubTotal               DOUBLE              NOT NULL COMMENT 'Sales subtotal. Computed as SUM(SalesOrderDetail.LineTotal)for the appropriate SalesOrderID.',
    TaxAmt                 DOUBLE              NOT NULL COMMENT 'Tax amount.',
    Freight                DOUBLE              NOT NULL COMMENT 'Shipping cost.',
    TotalDue               DOUBLE              NOT NULL COMMENT 'Total due from customer. Computed as Subtotal + TaxAmt + Freight.',
    Comment                TEXT COMMENT 'Sales representative comments.',
    OrderQty               SMALLINT            NOT NULL COMMENT 'Quantity ordered per product.',
    ProductID              INT                 NOT NULL COMMENT 'Product sold to customer. Foreign key to Product.ProductID.',
    UnitPrice              DOUBLE              NOT NULL COMMENT 'Selling price of a single product.',
    UnitPriceDiscount      DOUBLE              NOT NULL COMMENT 'Discount amount.',
    LineTotal              NUMERIC(38, 6)      NOT NULL COMMENT 'Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.',
    rowguid                VARCHAR(100) UNIQUE NOT NULL COMMENT 'ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.',
    ModifiedDate           DATETIME            NOT NULL COMMENT 'Date and time the record was last updated.',
    PRIMARY KEY (SalesOrderID, SalesOrderDetailID)
)